/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_project;

import java.sql.*;
import javax.swing.*;

/**
 *
 * @author itisowen_
 */
public class Register extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    UiLogin log = new UiLogin();
    
    public boolean checkUser(String user1){
        PreparedStatement ps = null;
        ResultSet rs = null;
        boolean check = false;
        String sql = "select * from test where user=?";
        
        try{
            ps = MyConnection.getConnection().prepareStatement(sql);
            ps.setString(1, user1);
            
            rs = ps.executeQuery();
            
            if(rs.next()){
                check = true;         
            }
        }catch(SQLException ex){
            
        }
        
        return check;
    }
    
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        tf_pass = new javax.swing.JPasswordField();
        button1 = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_repass = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        tf_fname = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        tf_lastname = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        tf_car = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        tf_license = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        tf_phonenumber = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(35, 43, 43));
        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 254));
        jLabel1.setText("Username");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 23));

        tf_user.setBackground(new java.awt.Color(35, 43, 43));
        tf_user.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_user.setForeground(new java.awt.Color(254, 255, 255));
        tf_user.setText("username");
        tf_user.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_userFocusGained(evt);
            }
        });
        tf_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_userActionPerformed(evt);
            }
        });
        jPanel5.add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 371, 36));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 371, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 371, 10));

        tf_pass.setBackground(new java.awt.Color(35, 43, 43));
        tf_pass.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_pass.setForeground(new java.awt.Color(254, 255, 255));
        tf_pass.setText("12345678910");
        tf_pass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_passFocusGained(evt);
            }
        });
        tf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passActionPerformed(evt);
            }
        });
        jPanel5.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 371, 36));

        button1.setActionCommand("Sign up");
        button1.setBackground(new java.awt.Color(64, 64, 64));
        button1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("Sign up");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel5.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 370, 50));

        jLabel3.setBackground(new java.awt.Color(35, 43, 43));
        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 254));
        jLabel3.setText("Password");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, 23));

        jLabel4.setBackground(new java.awt.Color(35, 43, 43));
        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Sign in");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, -1, 23));

        tf_repass.setBackground(new java.awt.Color(35, 43, 43));
        tf_repass.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_repass.setForeground(new java.awt.Color(254, 255, 255));
        tf_repass.setText("12345678910");
        tf_repass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_repass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_repassFocusGained(evt);
            }
        });
        jPanel5.add(tf_repass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 371, 36));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 371, 10));

        jLabel2.setBackground(new java.awt.Color(35, 43, 43));
        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 254));
        jLabel2.setText("Firstname");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 23));

        tf_fname.setBackground(new java.awt.Color(35, 43, 43));
        tf_fname.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_fname.setForeground(new java.awt.Color(254, 255, 255));
        tf_fname.setText("Firstname");
        tf_fname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_fnameFocusGained(evt);
            }
        });
        tf_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fnameActionPerformed(evt);
            }
        });
        jPanel5.add(tf_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 371, 36));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 371, 10));

        jLabel5.setBackground(new java.awt.Color(35, 43, 43));
        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 254));
        jLabel5.setText("Lastname");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, 23));

        tf_lastname.setBackground(new java.awt.Color(35, 43, 43));
        tf_lastname.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_lastname.setForeground(new java.awt.Color(254, 255, 255));
        tf_lastname.setText("Lastname");
        tf_lastname.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_lastname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_lastnameFocusGained(evt);
            }
        });
        tf_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_lastnameActionPerformed(evt);
            }
        });
        jPanel5.add(tf_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 371, 36));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 371, 10));

        jLabel6.setBackground(new java.awt.Color(35, 43, 43));
        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 254));
        jLabel6.setText("Car brand");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, 23));

        tf_car.setBackground(new java.awt.Color(35, 43, 43));
        tf_car.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_car.setForeground(new java.awt.Color(254, 255, 255));
        tf_car.setText("Car brand");
        tf_car.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_car.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_carFocusGained(evt);
            }
        });
        tf_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_carActionPerformed(evt);
            }
        });
        jPanel5.add(tf_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 371, 36));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 371, 10));

        jLabel7.setBackground(new java.awt.Color(35, 43, 43));
        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 254));
        jLabel7.setText("License plate");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, 23));

        tf_license.setBackground(new java.awt.Color(35, 43, 43));
        tf_license.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_license.setForeground(new java.awt.Color(254, 255, 255));
        tf_license.setText("License plate");
        tf_license.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_license.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_licenseFocusGained(evt);
            }
        });
        tf_license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_licenseActionPerformed(evt);
            }
        });
        jPanel5.add(tf_license, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 371, 36));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 371, 10));

        jLabel8.setBackground(new java.awt.Color(35, 43, 43));
        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 254));
        jLabel8.setText("Phone number");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, 23));

        tf_phonenumber.setBackground(new java.awt.Color(35, 43, 43));
        tf_phonenumber.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        tf_phonenumber.setForeground(new java.awt.Color(254, 255, 255));
        tf_phonenumber.setText("Phone number");
        tf_phonenumber.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf_phonenumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_phonenumberFocusGained(evt);
            }
        });
        tf_phonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_phonenumberActionPerformed(evt);
            }
        });
        jPanel5.add(tf_phonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 371, 36));

        jSeparator8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 371, 10));

        jLabel9.setBackground(new java.awt.Color(35, 43, 43));
        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 255, 255));
        jLabel9.setText("Already have an account?");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, 23));

        jLabel10.setBackground(new java.awt.Color(35, 43, 43));
        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 254));
        jLabel10.setText("Confirm password");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, 23));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 255, 255));
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 30, 30));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel12MouseDragged(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
        });
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_userActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String fname1 = tf_fname.getText();
        String lname1= tf_lastname.getText();
        String user1 = tf_user.getText();
        String pass1 = String.valueOf(tf_pass.getPassword());
        String repass1 = String.valueOf(tf_repass.getPassword());
        String car1 = tf_car.getText();
        String license1 = tf_license.getText();
	String phonenumber1 = tf_phonenumber.getText();
        
        if(fname1.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter firstname");
        }
        else if(lname1.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter lastname");
        }
        else if(user1.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter username");
        }
        else if(pass1.equals("") || (!pass1.equals(repass1))){
            JOptionPane.showMessageDialog(null, "Please enter correct password");
        }
        else if(car1.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter car brand");
        }
        else if(license1.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter car license");
        }
	else if(phonenumber1.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter phonenumber");
        }
        else if(checkUser(user1) == true){
            JOptionPane.showMessageDialog(null, "This username is already exists");
        }
        else{
        PreparedStatement ps,ps2 = null;
        
        String sql = "INSERT INTO `test`(`fname`, `lname`, `user`, `pass`, `phonenumber`, `memclass`) VALUES (?,?,?,?,?,'sliver')";
        try {
            ps = MyConnection.getConnection().prepareStatement(sql);
            
            ps.setString(1, fname1);
            ps.setString(2, lname1);
            ps.setString(3, user1);
            ps.setString(4, pass1);
	    ps.setString(5, phonenumber1);
            if(ps.executeUpdate() > 0){
		sql = "INSERT INTO `carlist`(`car`, `license`, `user`, `book`) VALUES (?,?,?,'0')";
		ps2 = MyConnection.getConnection().prepareStatement(sql);
		ps2.setString(1, car1);
		ps2.setString(2, license1);
		ps2.setString(3, user1);
		if(ps2.executeUpdate() > 0 ){
		
                JOptionPane.showMessageDialog(null, "User add");
                log.setVisible(true);
                log.pack();
                log.setLocationRelativeTo(null);
                log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
		this.dispose();
            }
	    }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void tf_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fnameActionPerformed

    private void tf_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_lastnameActionPerformed

    private void tf_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_carActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_carActionPerformed

    private void tf_licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_licenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_licenseActionPerformed

    private void tf_phonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_phonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_phonenumberActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - xMouse, y);
    }//GEN-LAST:event_jLabel12MouseDragged

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel12MousePressed

    private void tf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void tf_fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_fnameFocusGained
       if(tf_fname.getText().equals("Firstname")){
	    tf_fname.setText("");
	}
    }//GEN-LAST:event_tf_fnameFocusGained

    private void tf_userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_userFocusGained
        if(tf_user.getText().equals("username")){
	    tf_user.setText("");
	}
    }//GEN-LAST:event_tf_userFocusGained

    private void tf_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_passFocusGained
        if(tf_pass.getText().equals("12345678910")){
	    tf_pass.setText("");
	}
    }//GEN-LAST:event_tf_passFocusGained

    private void tf_repassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_repassFocusGained
        if(tf_repass.getText().equals("12345678910")){
	    tf_repass.setText("");
	}
    }//GEN-LAST:event_tf_repassFocusGained

    private void tf_lastnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_lastnameFocusGained
        if(tf_lastname.getText().equals("Lastname")){
	    tf_lastname.setText("");
	}
    }//GEN-LAST:event_tf_lastnameFocusGained

    private void tf_carFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_carFocusGained
        if(tf_car.getText().equals("Car brand")){
	    tf_car.setText("");
	}
    }//GEN-LAST:event_tf_carFocusGained

    private void tf_licenseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_licenseFocusGained
        if(tf_license.getText().equals("License plate")){
	    tf_license.setText("");
	}
    }//GEN-LAST:event_tf_licenseFocusGained

    private void tf_phonenumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_phonenumberFocusGained
        if(tf_phonenumber.getText().equals("Phone number")){
	    tf_phonenumber.setText("");
	}
    }//GEN-LAST:event_tf_phonenumberFocusGained

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField tf_car;
    private javax.swing.JTextField tf_fname;
    private javax.swing.JTextField tf_lastname;
    private javax.swing.JTextField tf_license;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_phonenumber;
    private javax.swing.JPasswordField tf_repass;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
}
