/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_project;

import com.sun.org.apache.bcel.internal.generic.Select;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;

import javax.swing.JOptionPane;

/**
 *
 * @author fluke
 */
public class WelcomeAdmin extends javax.swing.JFrame {

	
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs,rs2,rs3,rs4 = null;
    Object selected, selected_car;
    private ImageIcon[] image = new ImageIcon[2];
    
    public WelcomeAdmin() {
        initComponents();
	ComboUpdate();
	CarComboUpdate();
    }
    
    public void ComboUpdate(){
	try{
	String sql = "SELECT * FROM `test`";
	con = MyConnection.getConnection();
	pst = con.prepareStatement(sql);
	rs = pst.executeQuery();
	
	while(rs.next()){
	    String user = rs.getString("user");
	    c_user.addItem(user);
	}
	
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
    }
    
    public void CarComboUpdate(){
	car_com.removeAllItems();
	try{
	String sql = "SELECT * FROM `carlist` WHERE user = ?";
	con = MyConnection.getConnection();
	pst = con.prepareStatement(sql);
	pst.setString(1, (String) selected);
	rs3 = pst.executeQuery();
	
	while(rs3.next()){
	    String user = rs3.getString("car");
	    car_com.addItem(user);
	}
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
    }
    
    
    
    public void UpdateForm(String user){
	CarComboUpdate();
	try{
	    String sql = "SELECT * FROM `test` WHERE user = ? ";
	    con = MyConnection.getConnection();
	    pst = con.prepareStatement(sql);
	    pst.setString(1, user);
	    rs2 = pst.executeQuery();
	    while((rs2!=null) && (rs2.next())){
                t_first.setText(rs2.getString("fname"));
                t_last.setText(rs2.getString("lname"));
            }
	    
	    
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        c_user = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_first = new javax.swing.JTextField();
        t_last = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tc_add = new javax.swing.JTextField();
        tl_add = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        t_license = new javax.swing.JTextField();
        addcar = new javax.swing.JButton();
        car_com = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        c_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_userActionPerformed(evt);
            }
        });

        jLabel1.setText("User");

        jLabel2.setText("Firstname");

        jLabel3.setText("Lastname");

        jLabel4.setText("Car");

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("ADD CAR");

        jLabel6.setText("CAR");

        jLabel7.setText("LIncen");

        jLabel8.setText("License");

        t_license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_licenseActionPerformed(evt);
            }
        });

        addcar.setText("ADD");
        addcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcarActionPerformed(evt);
            }
        });

        car_com.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_comActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui_project/car1.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_first)
                            .addComponent(c_user, 0, 260, Short.MAX_VALUE))
                        .addGap(192, 192, 192)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_last, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(t_license)
                            .addComponent(car_com, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(37, 37, 37)
                                        .addComponent(tc_add, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tl_add))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(addcar)
                                .addGap(50, 50, 50))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel9)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(t_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(t_last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tl_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(tc_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(car_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addcar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t_license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(159, 159, 159))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_userActionPerformed
	JComboBox combo = (JComboBox) evt.getSource();
	this.selected = combo.getSelectedItem();
	UpdateForm((String) this.selected);
    }//GEN-LAST:event_c_userActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	PreparedStatement ps = null;
	try{
	String sql = "UPDATE `test` SET fname = ?, lname = ? WHERE user = ?";
	ps = con.prepareStatement(sql);
	ps.setString(1, t_first.getText());
	ps.setString(2, t_last.getText());
	ps.setString(3, (String) this.selected);
	if(ps.executeUpdate() > 0){
	    JOptionPane.showMessageDialog(null, "Update");
	}
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
	try{
	    String sql = "UPDATE `carlist` SET `license`= ? WHERE `user` = ? AND `car` = ?";
	    ps = con.prepareStatement(sql);
	    ps.setString(1, t_license.getText());
	    ps.setString(2, (String) this.selected);
	    ps.setString(3, (String) this.selected_car);
	    if(ps.executeUpdate() > 0){
	    JOptionPane.showMessageDialog(null, "Update");
	}
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_licenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_licenseActionPerformed

    private void car_comActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_comActionPerformed
	JComboBox combo = (JComboBox) evt.getSource();
	this.selected_car = combo.getSelectedItem();
	try{
	    String sql = "SELECT * FROM `carlist` WHERE user = ? AND car = ?";
	    con = MyConnection.getConnection();
	    pst = con.prepareStatement(sql);
	    pst.setString(1, (String) this.selected);
	    pst.setString(2, (String) this.selected_car);
	    rs4 = pst.executeQuery();
	    while((rs4!=null) && (rs4.next())){
		t_license.setText(rs4.getString("license"));
            }
	    
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
    }//GEN-LAST:event_car_comActionPerformed

    private void addcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcarActionPerformed
        if(!tc_add.getText().equals("")){
	    try{
	    String sql = "INSERT INTO `carlist`(`car`, `user`, `license`, `book`) VALUES (?, ?, ?, '0')";
	    con = MyConnection.getConnection();
	    pst = con.prepareStatement(sql);
	    pst.setString(1, tc_add.getText());
	    pst.setString(3, tl_add.getText());
	    pst.setString(2, (String) selected);
	    
	    if(pst.executeUpdate() > 0){
		JOptionPane.showMessageDialog(null, "Add");
		CarComboUpdate();
		tc_add.setText("");
		tl_add.setText("");
	    }
	    
	}catch(Exception e){
	    JOptionPane.showMessageDialog(null, e);
	}
	}
	else{
	    JOptionPane.showMessageDialog(null, "error");
	}
    }//GEN-LAST:event_addcarActionPerformed
    
    boolean count = false;
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
	image[0] = new ImageIcon(getClass().getResource("car1.png"));
	image[1] = new ImageIcon(getClass().getResource("car2.png"));
	if(!count){
	    jLabel9.setIcon(image[0]);
	    count = true;
	}
	else{
	    jLabel9.setIcon(image[1]);
	    count = false;
	}
    }//GEN-LAST:event_jLabel9MouseClicked

    public static void main(String args[]) {
	
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcar;
    private javax.swing.JComboBox<String> c_user;
    private javax.swing.JComboBox<String> car_com;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t_first;
    private javax.swing.JTextField t_last;
    private javax.swing.JTextField t_license;
    private javax.swing.JTextField tc_add;
    private javax.swing.JTextField tl_add;
    // End of variables declaration//GEN-END:variables
}
